"""
Wellness Progress Reasoning — "why am I not progressing?" engine.

Deterministic-first, same pattern as recommend.py/deriveJourneyState
(WellnessJourney.tsx): every FACT here is arithmetic over the user's own
wellness_goals/wellness_activities/wellness_checkins rows, never invented.
HYPOTHESES (possible contributing factors) are generated by rule, each tied
to a specific fact and labeled with a confidence tier — the caller
(main.py's _format_wellness_progress_context) is responsible for rendering
facts and hypotheses in clearly separate blocks and instructing the LLM to
never state a hypothesis as settled, never diagnose a medical condition,
and never blame the user.

This module NEVER calls an LLM itself — it only computes and structures
data. Phrasing happens downstream, same division of responsibility as
recommend.py/wellness.py.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import date, datetime, timezone
from typing import Any, Dict, List, Optional

from .wellness_profile import list_profile_signals, split_facts_and_hypotheses

_ANALYSIS_WINDOW_DAYS = 30
_PRIOR_WINDOW_DAYS = 30  # the 30 days before the analysis window, for a trend comparison
_CHECKIN_WINDOW_DAYS = 14
_MIN_ACTIVITIES_FOR_ANALYSIS = 3
_MIN_CHECKINS_FOR_SIGNAL_TREND = 3


def _parse_date(value: Optional[str]) -> Optional[date]:
    if not value:
        return None
    try:
        return date.fromisoformat(str(value)[:10])
    except (ValueError, TypeError):
        return None


def _days_ago(d: Optional[date], today: date) -> Optional[int]:
    if d is None:
        return None
    return (today - d).days


def _current_streak(activity_dates: List[date], today: date) -> int:
    """Mirrors computeCurrentStreak in WellnessJourney.tsx exactly (same
    "start from yesterday if today's empty" rule) so the chat answer and
    the Wellness Journey page never disagree about the user's own streak."""
    days = set(activity_dates)
    cursor = today if today in days else today.fromordinal(today.toordinal() - 1)
    streak = 0
    while cursor in days:
        streak += 1
        cursor = cursor.fromordinal(cursor.toordinal() - 1)
    return streak


@dataclass
class Hypothesis:
    text: str
    confidence: str  # "low" | "medium" | "high"
    based_on: List[str] = field(default_factory=list)


@dataclass
class ProgressAnalysis:
    status: str  # "ok" | "no_goal" | "insufficient_data" | "unauthenticated"
    goal: Optional[Dict[str, Any]] = None
    facts: Dict[str, Any] = field(default_factory=dict)
    hypotheses: List[Dict[str, Any]] = field(default_factory=list)
    missing_information: List[str] = field(default_factory=list)
    clarifying_question: Optional[str] = None
    suggested_next_action: Optional[str] = None


async def _user_id_from_token(token: Optional[str]) -> Optional[str]:
    if not token:
        return None
    import backend.main as backend_main  # lazy: see tools/__init__.py docstring

    try:
        claims = await backend_main.verify_jwt(token)
    except Exception:
        return None
    return claims.get("sub")


def _pick_priority_goal(goals: List[Dict[str, Any]]) -> Optional[Dict[str, Any]]:
    active = [g for g in goals if not g.get("is_completed")]
    if not active:
        return None
    # Most recently created active goal — same "priority goal" convention
    # the Wellness Journey page itself uses (most recent, not oldest).
    return sorted(active, key=lambda g: str(g.get("created_at") or ""), reverse=True)[0]


def _analyze(
    goal: Dict[str, Any],
    activities: List[Dict[str, Any]],
    checkins: List[Dict[str, Any]],
    today: date,
) -> ProgressAnalysis:
    goal_id = goal.get("id")
    goal_created = _parse_date(goal.get("created_at")) or today
    days_since_goal_created = max(1, _days_ago(goal_created, today) or 1)

    goal_activities = [a for a in activities if a.get("goal_id") == goal_id] if goal_id else activities
    all_dates = sorted({d for d in (_parse_date(a.get("activity_date")) for a in activities) if d}, reverse=True)
    goal_dates = sorted({d for d in (_parse_date(a.get("activity_date")) for a in goal_activities) if d}, reverse=True)

    window_start = today.fromordinal(today.toordinal() - _ANALYSIS_WINDOW_DAYS)
    prior_start = window_start.fromordinal(window_start.toordinal() - _PRIOR_WINDOW_DAYS)

    active_days_window = {d for d in all_dates if window_start <= d <= today}
    active_days_prior = {d for d in all_dates if prior_start <= d < window_start}

    analyzable_days = min(_ANALYSIS_WINDOW_DAYS, days_since_goal_created)
    consistency_rate = round(len(active_days_window) / analyzable_days, 2) if analyzable_days else 0.0

    days_since_last_activity = _days_ago(all_dates[0], today) if all_dates else None
    days_since_last_goal_activity = _days_ago(goal_dates[0], today) if goal_dates else None
    streak = _current_streak(all_dates, today)

    recent_checkins = [
        c for c in checkins
        if (d := _parse_date(c.get("checkin_date"))) and (today - d).days <= _CHECKIN_WINDOW_DAYS
    ]

    def _avg_signal(key: str) -> Optional[float]:
        values = [c["signals"][key] for c in recent_checkins if isinstance(c.get("signals"), dict) and key in c["signals"]]
        if len(values) < _MIN_CHECKINS_FOR_SIGNAL_TREND:
            return None
        return round(sum(values) / len(values), 2)

    energy_avg = _avg_signal("energy")
    sleep_avg = _avg_signal("sleep")
    stress_avg = _avg_signal("stress")

    facts: Dict[str, Any] = {
        "goal_title": goal.get("title"),
        "goal_type": goal.get("goal_type"),
        "current_value": goal.get("current_value"),
        "target_value": goal.get("target_value"),
        "unit": goal.get("unit"),
        "days_since_goal_created": days_since_goal_created,
        "total_activities_logged": len(activities),
        "activities_logged_against_this_goal": len(goal_activities),
        "active_days_last_30": len(active_days_window),
        "active_days_prior_30": len(active_days_prior),
        "consistency_rate_last_30": consistency_rate,
        "current_streak_days": streak,
        "days_since_last_activity": days_since_last_activity,
        "days_since_last_activity_for_this_goal": days_since_last_goal_activity,
        "checkins_in_last_14_days": len(recent_checkins),
        "avg_energy_last_14_days": energy_avg,
        "avg_sleep_hours_or_rating_last_14_days": sleep_avg,
        "avg_stress_last_14_days": stress_avg,
    }

    missing_information: List[str] = []
    if not activities:
        missing_information.append("No activity has been logged yet, so consistency can't be assessed.")
    if not checkins:
        missing_information.append("No daily check-ins yet, so energy/sleep/stress trends aren't available.")
    if goal_id and not goal_activities and activities:
        missing_information.append(
            "Activities have been logged, but none are linked to this specific goal — progress toward it may be "
            "happening but not being counted."
        )

    if len(activities) < _MIN_ACTIVITIES_FOR_ANALYSIS and not checkins:
        return ProgressAnalysis(
            status="insufficient_data",
            goal=goal,
            facts=facts,
            missing_information=missing_information,
            clarifying_question=(
                "There isn't enough logged yet for me to tell what's really going on. Have you been doing "
                "anything toward this goal that just hasn't been logged in the app — or has it been hard to "
                "get started at all?"
            ),
            suggested_next_action="Log one activity today, even a small one — that's enough to start telling a real pattern apart from too little data.",
        )

    hypotheses: List[Hypothesis] = []

    if consistency_rate < 0.25 and (days_since_last_activity or 0) >= 3:
        hypotheses.append(
            Hypothesis(
                text="Activity has been infrequent recently — inconsistent logging is the single most common "
                "reason progress stalls, more often than the approach itself being wrong.",
                confidence="high" if consistency_rate < 0.15 else "medium",
                based_on=[f"consistency_rate_last_30={consistency_rate}", f"days_since_last_activity={days_since_last_activity}"],
            )
        )

    if len(active_days_prior) >= 3 and len(active_days_window) < len(active_days_prior) * 0.5:
        hypotheses.append(
            Hypothesis(
                text="Activity has dropped off compared to the previous month — something may have changed "
                "recently (schedule, motivation, or circumstances) rather than this being a steady pattern.",
                confidence="medium",
                based_on=[f"active_days_last_30={len(active_days_window)}", f"active_days_prior_30={len(active_days_prior)}"],
            )
        )

    if energy_avg is not None and energy_avg <= 2.5:
        hypotheses.append(
            Hypothesis(
                text="Recent check-ins show lower energy than usual — low energy can make it harder to stay "
                "consistent, though it isn't possible to say from this alone whether energy is the cause or "
                "an effect of something else.",
                confidence="medium",
                based_on=[f"avg_energy_last_14_days={energy_avg}"],
            )
        )

    if stress_avg is not None and stress_avg >= 3.5:
        hypotheses.append(
            Hypothesis(
                text="Recent check-ins show higher stress than usual, which can crowd out time or motivation for "
                "a wellness routine.",
                confidence="medium",
                based_on=[f"avg_stress_last_14_days={stress_avg}"],
            )
        )

    if goal_id and goal_activities and not missing_information and goal.get("target_value"):
        current = goal.get("current_value") or 0
        target = goal["target_value"]
        if goal.get("goal_type") not in ("energy", "stress", "digestion", "skin", "general") and current == 0:
            hypotheses.append(
                Hypothesis(
                    text="Activity is being logged, but no progress value has moved toward the target yet — "
                    "worth checking whether logged activities are actually being counted toward this goal.",
                    confidence="low",
                    based_on=[f"current_value={current}", f"target_value={target}"],
                )
            )

    clarifying_question = None
    if not hypotheses or all(h.confidence == "low" for h in hypotheses):
        clarifying_question = (
            "Based on what's tracked, I can't tell for sure what's holding this back. Has anything changed "
            "recently — your routine, sleep, stress, or how you're using any product tied to this goal?"
        )

    if streak == 0 and (days_since_last_activity or 99) <= 1:
        suggested_next_action = "Keep today's momentum going with one more small action toward this goal."
    elif consistency_rate < 0.25:
        suggested_next_action = "Try the smallest possible version of this goal's activity today — the aim is rebuilding a streak, not a big session."
    else:
        suggested_next_action = "Consistency looks reasonable — a daily check-in for the next few days would surface whether energy, sleep, or stress is the missing piece."

    return ProgressAnalysis(
        status="ok",
        goal=goal,
        facts=facts,
        hypotheses=[h.__dict__ for h in hypotheses],
        missing_information=missing_information,
        clarifying_question=clarifying_question,
        suggested_next_action=suggested_next_action,
    )


async def run(token: Optional[str], message: str) -> Dict[str, Any]:
    import backend.main as backend_main  # lazy: see tools/__init__.py docstring

    user_id = await _user_id_from_token(token)
    if not user_id:
        return {"status": "unauthenticated"}

    goals = await backend_main.supabase_select(
        token, "wellness_goals",
        columns="id,goal_type,title,target_value,current_value,unit,is_completed,created_at",
        filters={"user_id": user_id}, limit=50,
    )
    goal = _pick_priority_goal(goals)
    if not goal:
        return {
            "status": "no_goal",
            "clarifying_question": "You don't have an active wellness goal set yet, so there's nothing to measure "
            "progress against. What would you like to work on?",
        }

    activities = await backend_main.supabase_select(
        token, "wellness_activities", columns="goal_id,activity_date,activity_type,value",
        filters={"user_id": user_id}, limit=200,
    )
    checkins = await backend_main.supabase_select(
        token, "wellness_checkins", columns="checkin_date,signals",
        filters={"user_id": user_id}, limit=60,
    )

    today = datetime.now(timezone.utc).date()
    analysis = _analyze(goal, activities, checkins, today)
    result = analysis.__dict__.copy()

    # Wellness Profile signals — facts are stated as-is, hypotheses about
    # the USER (not about progress) are surfaced separately so the caller
    # can apply the same never-present-as-confirmed rule as
    # _format_wellness_context.
    signals = await list_profile_signals(token, user_id)
    profile_facts, profile_hypotheses = split_facts_and_hypotheses(signals)
    result["profile_facts"] = profile_facts
    result["profile_hypotheses"] = profile_hypotheses
    return result
